In [2]:
import numpy as np

In [35]:
a = np.array([1,2,3,4,5])
print(a.shape)

(5,)


In [36]:
a = a[:, np.newaxis]
print(a.shape)
print(a)

(5, 1)
[[1]
 [2]
 [3]
 [4]
 [5]]


In [37]:

tmp = a

for i in range(len(a)-1):
    a = np.concatenate([a,tmp],-1)
a = np.expand_dims(a, axis=1)
print(a.shape)
print(a)

(5, 1, 5)
[[[1 1 1 1 1]]

 [[2 2 2 2 2]]

 [[3 3 3 3 3]]

 [[4 4 4 4 4]]

 [[5 5 5 5 5]]]


In [34]:
a = np.transpose(a)
print(a.shape)
print(a)

(6, 1, 5)
[[[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]

 [[1 2 3 4 5]]]
